### ISSUE TITLE
Update landing page

### ISSUE THREAD

**Issue by mobyvb** [mobyvb/pull-pal#4]
Change the "update files" section to have a more realistic looking code diff. Get rid of "Existing code line" and "New code line" lines, and replace with something you might see on a real pull request. Make sure to keep the styling for added and removed lines.
Also try changing the body and content background colors to something more engaging.

---

files:index.html
base:gh-pages

**Comment by black-crowned-night-heron** [comment]
working on it

**Comment by black-crowned-night-heron** [comment]
I ran into a problem working on this:
```
%!w(*github.ErrorResponse=&{0xc0004ecfc0 Must have admin rights to Repository. [] <nil> https://docs.github.com/rest/reference/issues#remove-a-label-from-an-issue})
```

**Comment by black-crowned-night-heron** [comment]
working on it

**Comment by black-crowned-night-heron** [comment]
I ran into a problem working on this:
```
%!w(*github.ErrorResponse=&{0xc00030b170 Must have admin rights to Repository. [] <nil> https://docs.github.com/rest/reference/issues#remove-a-label-from-an-issue})
```

**Comment by black-crowned-night-heron** [comment]
working on it

**Comment by black-crowned-night-heron** [comment]
I ran into a problem working on this:
```
%!w(*errors.errorString=&{non-fast-forward update})
```

**Comment by black-crowned-night-heron** [comment]
working on it

**Comment by black-crowned-night-heron** [comment]
I ran into a problem working on this:
```
%!w(*errors.errorString=&{non-fast-forward update})
```

**Comment by black-crowned-night-heron** [comment]
working on it

**Comment by black-crowned-night-heron** [comment]
I ran into a problem working on this:
```
%!w(*errors.errorString=&{non-fast-forward update})
```

**Comment by black-crowned-night-heron** [comment]
working on it
